DELIMITER $$

CREATE FUNCTION months_old(dob DATE)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE months INT;
    SET months = TIMESTAMPDIFF(MONTH, dob, CURDATE());
    RETURN months;
END$$

DELIMITER ;
